export const API_ENDPOINTS = {
    LOGIN: '/login',
    REGISTER: '/register',
    LOGOUT: '/logout',
    ME: '/me',
    USERS: '/users',
    ROLES: '/roles',
    PERMISSIONS: '/permissions',
    BRANDS: '/brands',
    CATEGORIES: '/categories',
    PRODUCTS: '/products',
    PRODUCT_VARIANTS: '/product-variants',
    PRODUCT_SPECIFICATIONS: '/product-specifications',
    PRODUCT_IMAGES: '/product-images',
    CARTS: '/cart',
    CART_ITEMS: '/cart/items',
    ORDERS: '/orders',
    ORDER_ITEMS: '/order-items',
    PAYMENTS: '/payments',
    SHIPPING_ADDRESSES: '/shipping-addresses',
    STOCK_LOGS: '/stock-logs',
    REPORTS: '/reports',
}
