export const PERMISSIONS = {
    DASHBOARD: {
        VIEW: 'dashboard.view',
    },
    PRODUCTS: {
        VIEW: 'products.view',
        CREATE: 'products.create',
        UPDATE: 'products.update',
        DELETE: 'products.delete',
    },
    CATEGORIES: {
        VIEW: 'categories.view',
        CREATE: 'categories.create',
        UPDATE: 'categories.update',
        DELETE: 'categories.delete',
    },
    BRANDS: {
        VIEW: 'brands.view',
        CREATE: 'brands.create',
        UPDATE: 'brands.update',
        DELETE: 'brands.delete',
    },
    ORDERS: {
        VIEW: 'orders.view',
        CREATE: 'orders.create',
        UPDATE: 'orders.update',
        DELETE: 'orders.delete',
    },
    PAYMENTS: {
        VIEW: 'payments.view',
        CREATE: 'payments.create',
        UPDATE: 'payments.update',
        DELETE: 'payments.delete',
    },
    COUPONS: {
        VIEW: 'coupons.view',
        CREATE: 'coupons.create',
        UPDATE: 'coupons.update',
        DELETE: 'coupons.delete',
    },
    USERS: {
        VIEW: 'users.view',
        CREATE: 'users.create',
        UPDATE: 'users.update',
        DELETE: 'users.delete',
    },
    ROLES: {
        VIEW: 'roles.view',
        CREATE: 'roles.create',
        UPDATE: 'roles.update',
        DELETE: 'roles.delete',
    },
    PERMISSION: {
        VIEW: 'permissions.view',
        CREATE: 'permissions.create',
        UPDATE: 'permissions.update',
        DELETE: 'permissions.delete',
    },
    PRODUCT_VARIANTS: {
        VIEW: 'product_variants.view',
        CREATE: 'product_variants.create',
        UPDATE: 'product_variants.update',
        DELETE: 'product_variants.delete',
    },
    PRODUCT_VARIANT_IMAGES: {
        VIEW: 'product_variant_images.view',
        CREATE: 'product_variant_images.create',
        UPDATE: 'product_variant_images.update',
        DELETE: 'product_variant_images.delete',
    },
    PRODUCT_SPECIFICATIONS: {
        VIEW: 'product_specifications.view',
        CREATE: 'product_specifications.create',
        UPDATE: 'product_specifications.update',
        DELETE: 'product_specifications.delete',
    },
    NEWS_CATEGORIES: {
        VIEW: 'news_categories.view',
        CREATE: 'news_categories.create',
        UPDATE: 'news_categories.update',
        DELETE: 'news_categories.delete',
    },
    NEWS_POSTS: {
        VIEW: 'news_posts.view',
        CREATE: 'news_posts.create',
        UPDATE: 'news_posts.update',
        DELETE: 'news_posts.delete',
    },
    STOCK_LOGS: {
        VIEW: 'stock_logs.view',
        CREATE: 'stock_logs.create',
        UPDATE: 'stock_logs.update',
        DELETE: 'stock_logs.delete',
    },
}
