export {
    buildProductCards,
    buildColorOptions,
} from './productCardBuilder.js'

export {
    buildProductLink,
    getBestVariantByRom,
    getProductBrandId,
    getProductBrandName,
    getProductBrandSlug,
    getProductCategoryId,
    getProductCategoryName,
    getProductCategorySlug,
    getProductFallbackOldPrice,
    getProductFallbackPrice,
    getProductVariants,
    getStorageWeight,
    getVariantAvailableQuantity,
    getVariantColorName,
    getVariantColorValue,
    getVariantImage,
    getVariantImages,
    getVariantOldPrice,
    getVariantPrice,
    getVariantRom,
    getVisibleProductVariants,
    isActiveStatus,
    normalizeText,
    slugifyText,
    toNumberPrice,
} from './productCardUtils.js'
